### ISSUE TITLE
Attributre Error : 'OwnedIterator'  object has no attribute 'string_handle

### ISSUE THREAD

**Issue by jonnakutip** [gher-ulg/DINCAE#2]
**Describe the bug**

A description of what the bug is.

**To Reproduce**

I am trying to setup and run DINCAE but am getting an error 

**Environment**

 - operating system: Windows 10
 - Python version : 3.7
 - Tensorflow version : 2.0
 - DINCAE version
![DINCAE_error](https://user-images.githubusercontent.com/8187194/83377553-74ca0b00-a3f3-11ea-93c1-be36e7a99280.PNG)

**Full output**

varname  SST (112, 112)
data shape:  (100, 112, 112)
data range:  13.575001 30.225
sz  (100, 112, 112)
sz  (100, 112, 112)
Number of input variables:  10
regularization_L2_beta  0
enc_nfilter_internal  [16, 24, 36, 54]
nvar  10
nepoch_keep_missing  0
Traceback (most recent call last):

  File "E:\D BackUp\PPL Works\UdaySir\DINCAE-master\run_DINCAE.py", line 14, in <module>
    DINCAE.reconstruct_gridded_nc(filename,varname,outdir)

  File "E:\D BackUp\PPL Works\UdaySir\DINCAE-master\DINCAE\__init__.py", line 741, in reconstruct_gridded_nc
    **kwargs)

  File "E:\D BackUp\PPL Works\UdaySir\DINCAE-master\DINCAE\__init__.py", line 405, in reconstruct
    train_iterator_handle = sess.run(train_iterator.string_handle())

AttributeError: 'OwnedIterator' object has no attribute 'string_handle' 

**Input file**

Filename : " avhrr_sub_add_clouds_small.nc "

**Comment by Alexander-Barth** [comment]
You need to install TensorFlow version 1.15. DINCAE does not work with TensorFlow 2.0 which unfortunately has a very different API. I will clarify this in the README file.
